version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
    ports:
        - "8000:8000"
    network_mode: 'host'
#     depends_on:
#       - appbd

#   appbd:
#     image: mysql:5.7
#     command: --innodb-use-native-aio=0
#     restart: always
#     volumes:
#       - "./.docker/dbdata:/var/lib/mysql"
#     environment:
#       MYSQL_DATABASE: "development_mysql"
#       MYSQL_PASSWORD: "root"
#       MYSQL_ROOT_PASSWORD: "root"
#     ports:
#        - "33456:3306"
