version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: root

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app

  redis:
    image: redis:alpine
    expose:
      - 6379
